import {readFileSync,writeFileSync,mkdirSync,cpSync} from 'node:fs';
const root='planos/tasks/prototype-feedback-refinement/',evidence='docs/qa/evidence/prototype-feedback-refinement/task-07/';
mkdirSync(evidence,{recursive:true});
for(const [run,label] of [['2026-09-25T14-59-39-204Z','baseline'],['2026-09-25T15-00-13-034Z','returns'],['2026-09-25T15-02-46-639Z','closures']])cpSync('docs/qa/evidence/native-tests/'+run,evidence+label,{recursive:true});
let task=readFileSync(root+'task-07.md','utf8').replace('status: in_progress','status: completed').replaceAll('- [ ]','- [x]');
task=task.slice(0,task.indexOf('## Execution notes'))+`## Execution notes

Technical scope completed 2026-09-25 through [apply-task-07.mjs](apply-task-07.mjs). CE348 now arms a transient return only when an actual consequence/retreat caller reaches formation. Voluntary callers remain in Maps007–022; automatic retreat goes through CE44. The reward-stage arm was removed. CE51/52 arm route completion only after their final ReadingComplete reaches formation, after CE352/353, Irati and map revelation have finished. CE40/38 use native picture 90 for 30-frame fade to black, 24-frame hold and 30-frame tavern reveal; reduced motion skips the overlay and waits. CE45 redraws all dead heroes in the current fixed container/portrait positions and starts their native 180-frame moves together. WaitForReturnPresentation observes only those live moves before CE349 cleanup and choice creation. Its IDs live in Game_Temp; load clears them and a restored wait resolves without replay. No death, reward or eligibility fact is modified.

Consumer audit: switches 38–45 were confined to CE348's old once-only logic; switch 47 belonged to CE45/349/350 release, distinct from the still-live motion preference variable 47. CE350 is now inactive with no executable timer. Variable 48 names the consumed transient effect. Independent review confirmed callers and last-reading boundaries. Its suspected CE38 conditional nesting did not reproduce: the native 412 closes the disabled-Seguir branch before the root-level fade and CE45 call; IT-009 proves the effect with a valid returned party.

The historical 60-frame IT-009 plus UT-029/030/031 passed (4/4) before changing the sensor. Updated IT-009 then failed on the absence of 180-frame moves: [baseline](../../../docs/qa/evidence/prototype-feedback-refinement/task-07/baseline/). Final native commands selected IT-009/010/011/013 (**4/4 PASS**, exit 0, 144 seconds) and IT-052/053 (**2/2 PASS**, exit 0, 363.5 seconds). [Return receipts](../../../docs/qa/evidence/prototype-feedback-refinement/task-07/returns/) prove simultaneous positions/opacity, blocked input through frame 179, cleanup, all old losses on a later genuine return, no replay on redraw, saved-wait restoration, reduced motion and voluntary retreat. [Closure receipts](../../../docs/qa/evidence/prototype-feedback-refinement/task-07/closures/) prove both route orders, complete text/reward sequence, normal 30/24/30 movement values, no overlay for reduced motion, no-death continuation and saved reward safety.

Scoped self-review/deslop, JavaScript syntax and whitespace checks passed. Preserve native events, transient presentation wait/metadata, named variable and evolved canonical tests. Owned test browser/server/profile teardown completed. No commit, staging or remote action occurred. These are technical fixtures; normal/reduced-motion capture timing and human pacing/visual judgment remain in task 13.

Public QA/devlog recipe: return after a natural loss by confirmed retreat, automatic retreat or finishing an initial route. On a route completion, finish all discovery/Rheed/Irati/map text first. Observe the separate black pause/reveal, then all absences together before preparation controls. A later return includes older losses; hero/board/map visits and Continue into the reached tavern show their empty places directly. Use reduced motion for the immediate counterpart.
`;
writeFileSync(root+'task-07.md',task);
let graph=readFileSync(root+'tasks.md','utf8').replace('Tasks 01–06 have completed their technical scopes; task 07 is in progress.','Tasks 01–07 have completed their technical scopes; task 08 is in progress.');
graph=graph.replace('T-006/RETURN | in_progress','T-006/RETURN | completed').replace('T-004/SAVE | pending','T-004/SAVE | in_progress').replace('[task-07.md](task-07.md) is active','[task-08.md](task-08.md) is active').replace('Tasks 01–06 technical receipts','Tasks 01–07 technical receipts');
writeFileSync(root+'tasks.md',graph);
writeFileSync(root+'verification.md',readFileSync(root+'verification.md','utf8').replace('Task 07 is active; tasks 08–13 remain pending.','Task 07 completed T-006/RETURN: IT-009/010/011/013 and IT-052/053 passed (6/6), with native frame/lifecycle receipts in task-07.md. Task 08 is active; tasks 09–13 remain pending.'));
writeFileSync(root+'task-08.md',readFileSync(root+'task-08.md','utf8').replace('status: pending','status: in_progress').replace('Pending. No runtime change, test, fixture, screenshot or acceptance has been produced by task authoring.','Active 2026-09-25. The approved transient request/save-wait boundary and native toolbar/notice implementation are prepared in apply-task-08.mjs. IT-088/089 extend the existing persistence suite for actual same-file writes, observation-only progress, safe cursor restoration, failures and obsolete results. Baseline and final results are pending.'));
