import {readFileSync,writeFileSync,mkdirSync,cpSync} from 'node:fs';
const root='planos/tasks/prototype-feedback-refinement/',evidence='docs/qa/evidence/prototype-feedback-refinement/task-08/';
mkdirSync(evidence+'final',{recursive:true});
for(const [run,label] of [['2026-09-25T15-10-00-247Z','baseline'],['2026-09-25T17-08-23-223Z','visible-save-failure'],['2026-09-25T17-04-08-345Z','final/integration'],['2026-09-25T17-09-11-664Z','final/manual']])cpSync('docs/qa/evidence/native-tests/'+run,evidence+label,{recursive:true});
for(const id of ['IT-017','IT-018'])cpSync('docs/qa/evidence/native-tests/2026-09-25T15-12-45-373Z/'+id,evidence+'final/'+id,{recursive:true});
let task=readFileSync(root+'task-08.md','utf8').replace('status: in_progress','status: completed').replaceAll('- [ ]','- [x]');
task=task.slice(0,task.indexOf('## Execution notes'))+`## Execution notes

Technical scope completed 2026-09-25 through [apply-task-08.mjs](apply-task-08.mjs). CE3/38 now expose Configurações and Salvar campanha atual in the upper reserved strip; Settings uses the installed Options command and returns to its native focus. Three final assets are preloaded by CE351. CE3 authors the noninteractive native success picture/text; Presentation owns its 120-frame transient lifetime and clears it on a new attempt, consultation, transfer, scene exit or load. The current-file request accepts a stable valid formation even with an incomplete draft, rejects busy/transfer/absence/pending conditions, and uses the existing save wait to start AutosaveForce only after the native request cursor advances. No interpreter index is rewritten and sequence equality never skips this deliberate write.

Bridge tracks one transient scheduled/writing request and associates its actual promise with the requesting scene/system. Pending writes reject campaign mutations and repeated saves. Only that write's success shows Campanha salva. Valid manual failures retain native SaveCore failure feedback; manual success consumes the provider callback to avoid a duplicate automatic-save notice. A WeakMap associates only manual callbacks with their origin and discards them after the scene/system is replaced. Ordinary automatic-save callbacks remain delegated. Late results cannot alter another campaign's persistence diagnosis or show feedback in a destroyed scene. Load has no live request and clears a restored save wait without writing.

The new IT-088 baseline failed on the absent save control. Initial technical execution found two concrete presentation defects: SaveCore callbacks touching a destroyed scene, and a zero-duration raw Game_Picture move leaving the notice invisible. The native success screenshot then exposed duplicate provider feedback, which is now consumed for manual success only. The added immediate-second-save sensor found an old visible notice serialized as opacity 255 while a one-frame hide was pending. Presentation now reinitializes that static native picture at its current authored geometry with the required opacity immediately, using Game_Picture.show; the saved notice is opacity 0. All failing runs remain preserved, including [the serialized-notice failure](../../../docs/qa/evidence/prototype-feedback-refinement/task-08/visible-save-failure/).

Final command selecting IT-088/089: **2 selected, 2 PASS**, exit 0, 96.1 seconds; [final manual receipts/captures](../../../docs/qa/evidence/prototype-feedback-refinement/task-08/final/manual/). Coverage includes mouse/keyboard entry, incomplete draft, actual file1 writes, naturally read hero observation with unchanged campaign sequence, advanced saved cursor, Continue without a repeat write/notice, Options/focus, pending overlap/mutation, synchronous/asynchronous failures, last valid bytes, retry, immediate consecutive save and obsolete completion after Title. IT-027/038/047/074 passed in the [integration lot](../../../docs/qa/evidence/prototype-feedback-refinement/task-08/final/integration/) (4 retained scopes); the final notice-opacity correction does not alter their interface controls, inventory or preload paths. IT-017/018 also passed for unchanged automatic checkpoint serialization/failure behavior. Both save tests were repeated after the final correction.

Viewed the successful native frame: full toolbar labels and Campanha salva fit without covering heroes/Seguir; no second provider success notice remains. Source review/deslop, syntax and whitespace checks passed. Keep the native UI assets/data, bridge/presentation request lifecycle and canonical tests; source facts remain in CampaignRules, request/notice objects remain transient. Owned test resources were torn down. No commit, staging, remote operation or personal save replacement occurred. V-016/LIVE and human UI judgment remain with task 13.

Public QA/devlog recipe: save an incomplete or complete preparation with the upper-right control, observe Salvando… only during the actual write and Campanha salva afterward, then enter Continue through the fresh age gate. Read Ivaí/map introduction and save again to compare before/after completion; leaving without saving must restore the last successful file's fact. Settings and Quadro return preserve draft and focus.
`;
writeFileSync(root+'task-08.md',task);
let graph=readFileSync(root+'tasks.md','utf8').replace('Tasks 01–07 have completed their technical scopes; task 08 is in progress.','Tasks 01–08 have completed their technical scopes; task 09 is in progress.');
graph=graph.replace('T-004/SAVE | in_progress','T-004/SAVE | completed').replace('T-004/FINAL | pending','T-004/FINAL | in_progress').replace('[task-08.md](task-08.md) is active','[task-09.md](task-09.md) is active').replace('Tasks 01–07 technical receipts','Tasks 01–08 technical receipts');
writeFileSync(root+'tasks.md',graph);
writeFileSync(root+'verification.md',readFileSync(root+'verification.md','utf8').replace('Task 08 is active; tasks 09–13 remain pending.','Task 08 completed V-016/TECH/T-003/T-004/SAVE: final IT-088/089 passed (2/2), with IT-017/018 and IT-027/038/047/074 scopes retained as explained in task-08.md. Task 09 is active; tasks 10–13 remain pending.'));
writeFileSync(root+'task-09.md',readFileSync(root+'task-09.md','utf8').replace('status: pending','status: in_progress').replace('Pending. No runtime change, test, fixture, screenshot or acceptance has been produced by task authoring.','Active 2026-09-25. Map023 retains the approved two outcome actions but currently uses ordinary text choices. apply-task-09.mjs prepares equal ornamented 504×304 picture targets with native title/consequence text and cleanup. IT-054 is being extended for geometry, HIDE, keyboard and pointer action isolation; technical results are pending.'));
