import {readFileSync,writeFileSync,mkdirSync,cpSync} from 'node:fs';
const root='planos/tasks/prototype-feedback-refinement/',dest='docs/qa/evidence/prototype-feedback-refinement/task-09/';
mkdirSync(dest,{recursive:true});
for(const [run,label] of [['2026-09-25T17-12-16-359Z','baseline'],['2026-09-25T17-16-30-796Z','final']])cpSync('docs/qa/evidence/native-tests/'+run,dest+label,{recursive:true});
let task=readFileSync(root+'task-09.md','utf8').replace('status: in_progress','status: completed').replaceAll('- [ ]','- [x]');
task=task.slice(0,task.indexOf('## Execution notes'))+`## Execution notes

Technical scope completed 2026-09-25. [apply-task-09.mjs](apply-task-09.mjs) authors two equal 504×304 final ornamented plates at (112,208)/(664,208), with native 36px titles and 26px complete consequences. Both use the same PictureChoices focus treatment; the existing horizontal choice, input-release guard, ending action and checkpoint remain the owners. Preceding ensemble pictures and attachments are cleared, both targets are bound to HIDE, and each selected branch clears the panels before committing its outcome. CE351 preloads the final asset.

The extended IT-054 first failed on the absent panel geometry. Final command selecting IT-054/065 and UT-034: **3 selected, 3 PASS**, exit 0, 268.1 seconds; [baseline and final receipts](../../../docs/qa/evidence/prototype-feedback-refinement/task-09/). Four Council variants cover collective/mixed/solo and normal/reduced motion; pointer activation on title/body, both outcomes, left/right focus, HIDE restoration, unchanged state before activation, panel cleanup and exactly one ending save. IT-065 preserves FAST revocation at the final choice; UT-034 rejects repeated/invalid commitments. The native screenshot was inspected: complete title/consequence lines fit within equal panels and focus is visible. Source review/deslop and syntax checks passed. Test resources were torn down; no commit or remote action.

Public entry/devlog: from an own campaign, complete both initial routes, reach the final Council, finish every eligible opinion and stop at the two panels. Capture full consequences before deliberately choosing Reunir; reuse the own compatible Council checkpoint through Continue for Destruir. These technical fixtures do not create directed campaign provenance: S-004/live and final human visual acceptance remain task 13.
`;
writeFileSync(root+'task-09.md',task);
writeFileSync(root+'tasks.md',readFileSync(root+'tasks.md','utf8').replaceAll('Tasks 01–08','Tasks 01–09').replace('task 09 is in progress','task 10 is in progress').replace('T-004/FINAL | in_progress','T-004/FINAL | completed').replace('V-015/TECH | pending','V-015/TECH | in_progress').replace('[task-09.md](task-09.md) is active','[task-10.md](task-10.md) is active'));
writeFileSync(root+'verification.md',readFileSync(root+'verification.md','utf8').replace('Task 09 is active; tasks 10–13 remain pending.','Task 09 completed T-004/FINAL with IT-054/065 and UT-034 (3/3 PASS); see task-09.md for receipts and scope. Task 10 is active; tasks 11–13 remain pending.'));
writeFileSync(root+'task-10.md',readFileSync(root+'task-10.md','utf8').replace('status: pending','status: in_progress').replace('Pending. No runtime change, test, fixture, screenshot or acceptance has been produced by task authoring.','Active 2026-09-25. CE59 labels use fonts 18/20/24 on scaled 330×212 plates; native measurement and eight-deceased baseline capture are running before reflow. The coordinates in Show Picture are variable IDs, not literal overlapping positions. Source inscriptions and art/order remain authoritative.'));
