// Canonical `lib/source.ts` for Fumadocs.
//
// `loader()` is server-side, not build-time magic. It reads from a Fumadocs MDX
// collection (or a custom `StaticSource` / `DynamicSource`) and exposes a
// uniform API for pages, slugs, URLs, and a serialisable page tree.
//
// Adapt for the framework you're on (Next.js, React Router, TanStack Start,
// Waku) — the shape stays the same; only the import paths change.

import { loader } from "fumadocs-core/source";
import { docs } from "collections/server"; // generated by fumadocs-mdx
// import { i18n } from '@/lib/i18n';      // when i18n is configured
import { lucideIconsPlugin } from "fumadocs-core/source/lucide-icons";

// Single-source variant — most projects.
export const source = loader({
  source: docs.toFumadocsSource(),
  baseUrl: "/docs",

  // Optional: override the URL per-page (locale prefix, custom routing).
  // url: (slugs, locale) =>
  //   locale ? `/${locale}/docs/${slugs.join('/')}` : `/docs/${slugs.join('/')}`,

  // Optional: override slug extraction (return undefined to fallback).
  // slugs: (file) => undefined,

  // Optional: turn frontmatter `icon: 'Network'` into a ReactElement.
  // Fumadocs ships NO icon library — supply your own resolver.
  // icon: (name) => {
  //   if (!name) return undefined;
  //   const Icon = iconMap[name];
  //   return Icon ? createElement(Icon) : undefined;
  // },

  // Optional: i18n. Pass the same config used by `createI18nMiddleware`.
  // i18n,

  plugins: [lucideIconsPlugin()],
});

// Multi-source variant — when mixing docs with OpenAPI / blog / etc.
//
// import { openapiSource } from 'fumadocs-openapi/server';
// export const source = loader({
//   baseUrl: '/docs',
//   source: {
//     docs: docs.toFumadocsSource(),
//     openapi: openapiSource({ /* ... */ }),
//   },
// });
//
// Result objects carry a `type` discriminant — every consumer must branch
// on `page.type === 'page' | 'openapi' | ...`.

// Static export helpers (Next.js) — wire from the catch-all route:
//
// export async function generateStaticParams() {
//   return source.generateParams();
// }
