import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root = 'rpg-maker/The Dryland Drowned/';
const read = name => JSON.parse(fs.readFileSync(root+'data/'+name,'utf8'));
const events=read('CommonEvents.json'), map=read('Map003.json'), prologue=read('Map002.json');
assert.equal(events.length,82);
const c=(code,parameters=[],indent=0)=>({code,indent,parameters});
const pc=(plugin,name,args={})=>c(357,[plugin,name,name,args]);
const bridge=(name,args={})=>pc('Dryland_EventBridge',name,args);
const presentation=(name,args={})=>pc('Dryland_Presentation',name,args);
const call=id=>c(117,[id]);
const query=(kind,variable)=>bridge('Query',{kind,variable:String(variable)});
const nest=(list,indent)=>list.map(command=>({...structuredClone(command),indent:command.indent+indent}));
function append(name,list){const id=events.length;events.push({id,name,trigger:0,switchId:1,list:[...list,c(0)]});return id;}
function sections(event){
 const result={};let id;
 for(const command of event.list){
  if([108,408].includes(command.code)){
   for(const line of String(command.parameters[0]).split('\n')){
    if(line.startsWith('@dryland-section ')){id=line.slice(17);result[id]=[];}
    if(line==='@dryland-end')id=null;
   }
  }else if(id)result[id].push(structuredClone(command));
 }
 return result;
}
function reduced(list){
 const output=[];
 for(let i=0;i<list.length;i++){
  const command=list[i];
  if(command.code===657)continue;
  const duration=command.code===357 && command.parameters[3]['Duration:eval'];
  if(duration && Number(duration)>0){
   const immediate=structuredClone(command);immediate.parameters[3]['Duration:eval']='0';
   output.push(c(111,[12,'$gameVariables.value(47)']),...nest([immediate],1),c(411),...nest([command],1),c(412));
  }else if(command.code===230){
   output.push(c(111,[12,'!$gameVariables.value(47)']),...nest([command],1),c(412));
  }else output.push(command);
 }
 return output;
}
const roleIds={};
const oldHeroBranch=events[3].list.slice(9,49).map(cmd=>({...structuredClone(cmd),indent:cmd.indent-1}));
for(let hero=1;hero<=8;hero++){
 const old=events[hero+4], bodies=sections(old), name=old.name.replace('Herói — ','');
 roleIds[hero]={};
 for(const [role,title] of [['profile','Perfil'],['speech','Conversa'],['selection','Selecionado'],['party_full','Grupo cheio']]){
  roleIds[hero][role]=append(`${title} — ${name}`,[presentation('ObservationBegin'),presentation('MotionPreference',{variable:'47'}),...reduced(bodies[`${role}.H${hero}`]),presentation('ObservationComplete')]);
 }
 const list=[];
 for(let i=0;i<oldHeroBranch.length;i++){
  const command=oldHeroBranch[i],p=command.parameters;
  if(command.code===357 && p[0]==='Dryland_EventBridge' && p[1]==='Conversation')continue;
  if(command.code===122 && p[0]===21){
   const role=/^'(\w+)\.'/.exec(p[4])[1];
   if(role==='profile')for(let id=10;id<=44;id++)list.push(c(235,[id],command.indent));
   list.push(c(117,[roleIds[hero][role]],command.indent));
   assert.equal(oldHeroBranch[++i].parameters[1],'Present');
   continue;
  }
  list.push(command);
 }
 old.name=`Interagir — ${name}`;old.list=[...list,c(0)];
 const entry=structuredClone(map.events[2]);entry.id=map.events.length;entry.name=name;entry.x=hero+1;
 entry.pages[0].list=[c(122,[22,22,0,4,JSON.stringify(`H${hero}`)]),bridge('CaptureContext'),call(old.id),c(0)];map.events.push(entry);
}
const dispatch=[];
for(let hero=1;hero<=8;hero++)dispatch.push(c(111,[12,`$gameVariables.value(22) === 'H${hero}'`],1),c(117,[hero+4],2),c(412,[],1));
events[3].list.splice(9,40,...dispatch);
// Helpers are ordinary native calls; the former ownership markers are removed.
for(const id of [76,80,81])events[id].list=reduced(events[id].list.filter(command=>![108,408].includes(command.code)));
const prologueBodies=sections(events[1]);const units=[];
for(const [id,list] of Object.entries(prologueBodies))units.push(append(`Prólogo — ${id}`,[query('sequence',148),query('passageId',149),...list,bridge('ReadingComplete',{passageVariable:'149',contextVariable:'148'})]));
events[1].list=[...units.map(call),c(0)];
const list=prologue.events[1].pages[0].list;
const start=list.findIndex(cmd=>cmd.code===112),end=list.findIndex(cmd=>cmd.code===413);
list.splice(start,end-start+1,call(1),call(44));
prologue.events[1].name='Prólogo';
// Remove orphan annotations from the historical Action/checkpoint insertion.
prologue.events[1].pages[0].list=list.filter(cmd=>cmd.code!==657);
const context={};vm.runInNewContext(fs.readFileSync(root+'js/plugins.js','utf8'),context);
assert.ok(!context.$plugins.some(p=>p.name==='Dryland_Presentation'));
context.$plugins.push({name:'Dryland_Presentation',status:true,description:'Integração de apresentação nativa',parameters:{}});
fs.writeFileSync(root+'js/plugins.js','// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n'+context.$plugins.map(p=>JSON.stringify(p)).join(',\n')+'\n];\n');
fs.writeFileSync(root+'data/CommonEvents.json','[\n'+events.map(e=>JSON.stringify(e)).join(',\n')+'\n]\n');
for(const [name,value] of [['Map003.json',map],['Map002.json',prologue]])fs.writeFileSync(root+'data/'+name,JSON.stringify(value,null,2)+'\n');
console.log(JSON.stringify({roleIds,prologue:units}));
