import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root = 'rpg-maker/The Dryland Drowned/';
const read = name => JSON.parse(fs.readFileSync(root + 'data/' + name, 'utf8'));
const events = read('CommonEvents.json'), system = read('System.json'), map = read('Map003.json');
assert.equal(events[4].name, 'Campanha — Metadados');
assert.equal(system.variables.length, 147);
const declarations = events[4].list.filter(c => c.code === 108).map(c => {
  const [, kind, value] = /^@(\w+) (.*)$/.exec(c.parameters[0]);
  return { kind, ...JSON.parse(value) };
});
const command = (name, args) => ({ code: 357, indent: 0, parameters: ['Dryland_EventBridge', name, name, args] });
events[4].name = 'Configuração do jogo';
events[4].list = declarations.filter(d => d.kind !== 'competency').map(d => command(
  {hero:'ConfigureHero',route:'ConfigureRoute',encounter:'ConfigureEncounter'}[d.kind], {id:d.id,name:d.name}
));
events[4].list.push({code:0,indent:0,parameters:[]});
const query = (kind, variable) => command('Query', {kind, id:'', index:'0', variable:String(variable), switch:'0'});
const fields = {phase:31, dungeonId:34, endingId:59};
for (const c of events[67].list) {
  c.parameters = c.parameters.map(p => typeof p === 'string' ? p
    .replaceAll('$gameSystem._dryland.campaign.reading?.passageIds[$gameSystem._dryland.campaign.reading.index]', '$gameVariables.value(56)')
    .replaceAll('$gameSystem._dryland.campaign.reading?.index', '$gameVariables.value(58)')
    .replace(/\$gameSystem\._dryland\.campaign\.(phase|dungeonId|endingId)/g, (_, key) => `$gameVariables.value(${fields[key]})`) : p);
}
events[67].list.unshift(...Object.entries(fields).map(([key,id]) => query(key,id)),query('passageId',56),query('readingIndex',58));
const entry = structuredClone(map.events[1]);
entry.id = map.events.length; entry.name = 'Configuração do jogo'; entry.x = 1; entry.y = 1;
entry.pages[0].trigger = 0;
entry.pages[0].list = [{code:117,indent:0,parameters:[4]},{code:0,indent:0,parameters:[]}];
map.events.push(entry);
const names = ['Campanha — sequência consultada','Leitura — contexto capturado','Leitura — passagem capturada'];
system.variables.push(...names);
const context = {}; vm.runInNewContext(fs.readFileSync(root+'js/plugins.js','utf8'),context);
const bridge = context.$plugins.filter(p=>p.name==='Dryland_EventBridge'); assert.equal(bridge.length,1);
bridge[0].parameters.ConfigurationCommonEvent = '4';
// Preserve MZ's one-object-per-line database format.
fs.writeFileSync(root+'data/CommonEvents.json','[\n'+events.map(e=>JSON.stringify(e)).join(',\n')+'\n]\n');
for (const [name,value] of [['Map003.json',map],['System.json',system]]) fs.writeFileSync(root+'data/'+name,JSON.stringify(value, null, name === 'Map003.json' ? 2 : undefined)+'\n');
fs.writeFileSync(root+'js/plugins.js','// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n'+context.$plugins.map(p=>JSON.stringify(p)).join(',\n')+'\n];\n');
for(const name of ['CommonEvents.json','Map003.json','System.json']) read(name);
console.log('Updated CE4, CE67, Map003 configuration entry, variables 147–149, Bridge parameter.');
